apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      restartPolicy: Always
      containers:
        - name: alertmanager
          image: quay.io/prometheus/alertmanager:v0.27.0
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 9093
              protocol: TCP
          volumeMounts:
            - name: alertmanager-cm0
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
          livenessProbe:
            exec:
              command:
                - wget
                - --quiet
                - --tries=1
                - --spider
                - http://localhost:9093/-/healthy
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 3
      volumes:
        - name: alertmanager-cm0
          configMap:
            name: alertmanager-cm0
