{{- if .Values.redis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "opsnexus.componentFullname" (dict "root" . "component" "redis")) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "opsnexus.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
data:
  redis.conf: |
{{ .Files.Get "files/redis/redis.conf" | indent 4 }}
{{- end }}

