{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "opsnexus.componentFullname" (dict "root" . "component" "prometheus")) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "opsnexus.componentLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.global.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.global.evaluationInterval }}

{{- if .Values.prometheus.alerting.enabled }}
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - {{ include "opsnexus.prometheusAlertmanagerTarget" . | quote }}
{{- end }}

    rule_files: []

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
            labels:
              app: prometheus
{{- if .Values.pushgateway.enabled }}
      - job_name: pushgateway
        honor_labels: true
        static_configs:
          - targets:
              - {{ printf "%s:%v" (include "opsnexus.componentFullname" (dict "root" . "component" "pushgateway")) .Values.pushgateway.service.port | quote }}
{{- end }}
{{- with .Values.prometheus.extraScrapeConfigs }}
{{ toYaml . | indent 6 }}
{{- end }}
{{- end }}

