{{- if not .Values.api.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsnexus.apiSecretName" . }}
  labels:
    {{- include "opsnexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.existingSecretKeys.agentHeartbeatToken }}: {{ .Values.api.monitor.agentHeartbeatToken | quote }}
  {{ .Values.api.existingSecretKeys.webhookToken }}: {{ .Values.api.monitor.webhookToken | quote }}
{{- end }}

