{{- if and (not .Values.redis.auth.existingSecret) (not .Values.externalServices.redis.existingSecret) (or .Values.redis.enabled .Values.externalServices.redis.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsnexus.redisSecretName" . }}
  labels:
    {{- include "opsnexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.redis.enabled }}
  {{ .Values.redis.auth.passwordKey }}: {{ .Values.redis.auth.password | quote }}
  {{- else }}
  {{ .Values.externalServices.redis.passwordKey }}: {{ .Values.externalServices.redis.password | quote }}
  {{- end }}
{{- end }}

