{{- if and .Values.alertmanager.enabled (not .Values.alertmanager.existingConfigSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-alertmanager-config" (include "opsnexus.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "opsnexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: {{ .Values.alertmanager.config.resolveTimeout }}

    route:
      receiver: {{ .Values.alertmanager.config.receiverName }}
      group_by:
{{ toYaml .Values.alertmanager.config.groupBy | indent 8 }}
      group_wait: {{ .Values.alertmanager.config.groupWait }}
      group_interval: {{ .Values.alertmanager.config.groupInterval }}
      repeat_interval: {{ .Values.alertmanager.config.repeatInterval }}

    receivers:
      - name: {{ .Values.alertmanager.config.receiverName }}
        webhook_configs:
          - url: {{ printf "http://%s:%v/api/v1/monitor/alerts/webhook?token=%s" (include "opsnexus.componentFullname" (dict "root" . "component" "api")) .Values.api.service.port .Values.api.monitor.webhookToken | quote }}
            send_resolved: true

    templates: []
{{- end }}

