{{- if and (not .Values.mysql.auth.existingSecret) (not .Values.externalServices.mysql.existingSecret) (or .Values.mysql.enabled .Values.externalServices.mysql.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsnexus.mysqlSecretName" . }}
  labels:
    {{- include "opsnexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.mysql.enabled }}
  {{ .Values.mysql.auth.rootPasswordKey }}: {{ .Values.mysql.auth.rootPassword | quote }}
  {{- else }}
  {{ .Values.externalServices.mysql.passwordKey }}: {{ .Values.externalServices.mysql.password | quote }}
  {{- end }}
{{- end }}

