apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: devops-api
  name: devops-api-cm0
data:
  config.yaml: |
    server:
      address: 0.0.0.0:8000
      model: debug

    db:
      dialects: mysql
      host: mysql
      port: 3306
      db: devops
      username: root
      password: devops@2025
      charset: utf8
      maxIdle: 50
      maxOpen: 150

    redis:
      address: redis:6379
      password: "devops@2025"

    imageSettings:
      uploadDir: ./upload/
      imageHost: ""

    log:
      path: ./log
      name: sys
      model: console

    monitor:
      prometheus:
        url: "http://prometheus:9090"
      pushgateway:
        url: "http://pushgateway:9091"
      agent:
        heartbeat_server_url: "http://devops-api:8000/api/v1/monitor/agent/heartbeat"
        heartbeat_token: "agent-heartbeat-token-2024"
      webhook:
        token: "webhook-notify-token-2024"
