ALTER TABLE sys_users
    ADD COLUMN IF NOT EXISTS department_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE sys_menus
    ADD COLUMN IF NOT EXISTS menu_type VARCHAR(16) NOT NULL DEFAULT 'menu',
    ADD COLUMN IF NOT EXISTS permission VARCHAR(128) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS sys_departments (
    id BIGSERIAL PRIMARY KEY,
    parent_id BIGINT NOT NULL DEFAULT 0,
    dept_name VARCHAR(64) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    leader VARCHAR(64) NOT NULL DEFAULT '',
    phone VARCHAR(32) NOT NULL DEFAULT '',
    email VARCHAR(128) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);
