package k8s

import (
	"dodevops-api/api/k8s/controller"
	"dodevops-api/common"
	"dodevops-api/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterK8sRoutes(router *gin.RouterGroup) {
	kubeClusterCtrl := controller.NewKubeClusterController(common.GetDB())
	k8sNodesCtrl := controller.NewK8sNodesController(common.GetDB())
	k8sNamespaceCtrl := controller.NewK8sNamespaceControllerWithCache(common.GetDB(), common.GetRedisClient())
	k8sWorkloadCtrl := controller.NewK8sWorkloadController(common.GetDB())
	k8sEventsCtrl := controller.NewK8sEventsController(common.GetDB())
	k8sTerminalCtrl := controller.NewK8sTerminalController(common.GetDB())
	k8sKubectlCtrl := controller.NewK8sKubectlController(common.GetDB())
	k8sApplyCtrl := controller.NewK8sApplyController(common.GetDB())
	k8sServiceCtrl := controller.NewK8sServiceController(common.GetDB())
	k8sIngressCtrl := controller.NewK8sIngressController(common.GetDB())
	k8sStorageCtrl := controller.NewK8sStorageController(common.GetDB())
	k8sConfigCtrl := controller.NewK8sConfigController(common.GetDB())

	router.POST("/k8s/cluster", middleware.AuthMiddleware(), kubeClusterCtrl.CreateCluster)
	router.GET("/k8s/cluster/:id", middleware.AuthMiddleware(), kubeClusterCtrl.GetCluster)
	router.GET("/k8s/cluster", middleware.AuthMiddleware(), kubeClusterCtrl.GetClusterList)
	router.PUT("/k8s/cluster/:id", middleware.AuthMiddleware(), kubeClusterCtrl.UpdateCluster)
	router.DELETE("/k8s/cluster/:id", middleware.AuthMiddleware(), kubeClusterCtrl.DeleteCluster)
	router.GET("/k8s/cluster/:id/status", middleware.AuthMiddleware(), kubeClusterCtrl.GetClusterStatus)
	router.GET("/k8s/cluster/:id/detail", middleware.AuthMiddleware(), kubeClusterCtrl.GetClusterDetail)
	router.POST("/k8s/cluster/:id/sync", middleware.AuthMiddleware(), kubeClusterCtrl.SyncCluster)

	router.GET("/k8s/cluster/:id/nodes", middleware.AuthMiddleware(), k8sNodesCtrl.GetNodes)
	router.GET("/k8s/cluster/:id/nodes/:nodeName", middleware.AuthMiddleware(), k8sNodesCtrl.GetNodeDetail)
	router.GET("/k8s/cluster/:id/nodes/:nodeName/enhanced", middleware.AuthMiddleware(), k8sNodesCtrl.GetNodeDetailEnhanced)
	router.POST("/k8s/cluster/:id/nodes/:nodeName/taints", middleware.AuthMiddleware(), k8sNodesCtrl.AddTaint)
	router.DELETE("/k8s/cluster/:id/nodes/:nodeName/taints", middleware.AuthMiddleware(), k8sNodesCtrl.RemoveTaint)
	router.POST("/k8s/cluster/:id/nodes/:nodeName/labels", middleware.AuthMiddleware(), k8sNodesCtrl.AddLabel)
	router.DELETE("/k8s/cluster/:id/nodes/:nodeName/labels", middleware.AuthMiddleware(), k8sNodesCtrl.RemoveLabel)
	router.POST("/k8s/cluster/:id/nodes/:nodeName/cordon", middleware.AuthMiddleware(), k8sNodesCtrl.CordonNode)
	router.POST("/k8s/cluster/:id/nodes/:nodeName/drain", middleware.AuthMiddleware(), k8sNodesCtrl.DrainNode)
	router.GET("/k8s/cluster/:id/nodes/:nodeName/resources", middleware.AuthMiddleware(), k8sNodesCtrl.GetNodeResourceAllocation)

	router.GET("/k8s/cluster/:id/namespaces", middleware.AuthMiddleware(), k8sNamespaceCtrl.GetNamespaces)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName", middleware.AuthMiddleware(), k8sNamespaceCtrl.GetNamespace)
	router.POST("/k8s/cluster/:id/namespaces", middleware.AuthMiddleware(), k8sNamespaceCtrl.CreateNamespace)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName", middleware.AuthMiddleware(), k8sNamespaceCtrl.UpdateNamespace)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName", middleware.AuthMiddleware(), k8sNamespaceCtrl.DeleteNamespace)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/resourcequotas", middleware.AuthMiddleware(), k8sNamespaceCtrl.GetResourceQuotas)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/resourcequotas", middleware.AuthMiddleware(), k8sNamespaceCtrl.CreateResourceQuota)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/resourcequotas/:quotaName", middleware.AuthMiddleware(), k8sNamespaceCtrl.UpdateResourceQuota)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/resourcequotas/:quotaName", middleware.AuthMiddleware(), k8sNamespaceCtrl.DeleteResourceQuota)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/limitranges", middleware.AuthMiddleware(), k8sNamespaceCtrl.GetLimitRanges)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/limitranges", middleware.AuthMiddleware(), k8sNamespaceCtrl.CreateLimitRange)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/limitranges/:limitRangeName", middleware.AuthMiddleware(), k8sNamespaceCtrl.UpdateLimitRange)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/limitranges/:limitRangeName", middleware.AuthMiddleware(), k8sNamespaceCtrl.DeleteLimitRange)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/workloads", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetWorkloads)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/workloads/:type/:workloadName", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetWorkloadDetail)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/workloads/:type/:workloadName/autoscaling", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetWorkloadAutoscaling)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/workloads/:type/:workloadName/capacity-suggestion/history", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetWorkloadCapacitySuggestionHistory)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/workloads/:type/:workloadName/capacity-suggestion", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetWorkloadCapacitySuggestion)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/workloads/:type/:workloadName/governance-overview", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetWorkloadGovernanceOverview)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/workloads/:type/:workloadName/autoscaling", middleware.AuthMiddleware(), k8sWorkloadCtrl.UpsertWorkloadAutoscaling)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/workloads/:type/:workloadName/autoscaling", middleware.AuthMiddleware(), k8sWorkloadCtrl.DeleteWorkloadAutoscaling)

	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/deployments", middleware.AuthMiddleware(), k8sWorkloadCtrl.CreateDeployment)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName", middleware.AuthMiddleware(), k8sWorkloadCtrl.UpdateDeployment)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName", middleware.AuthMiddleware(), k8sWorkloadCtrl.DeleteDeployment)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName/scale", middleware.AuthMiddleware(), k8sWorkloadCtrl.ScaleDeployment)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName/restart", middleware.AuthMiddleware(), k8sWorkloadCtrl.RestartDeployment)

	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/statefulsets", middleware.AuthMiddleware(), k8sWorkloadCtrl.CreateStatefulSet)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/statefulsets/:statefulSetName", middleware.AuthMiddleware(), k8sWorkloadCtrl.UpdateStatefulSet)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/statefulsets/:statefulSetName", middleware.AuthMiddleware(), k8sWorkloadCtrl.DeleteStatefulSet)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/statefulsets/:statefulSetName/scale", middleware.AuthMiddleware(), k8sWorkloadCtrl.ScaleStatefulSet)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/statefulsets/:statefulSetName/restart", middleware.AuthMiddleware(), k8sWorkloadCtrl.RestartStatefulSet)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/daemonsets", middleware.AuthMiddleware(), k8sWorkloadCtrl.CreateDaemonSet)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/daemonsets/:daemonSetName", middleware.AuthMiddleware(), k8sWorkloadCtrl.UpdateDaemonSet)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/daemonsets/:daemonSetName", middleware.AuthMiddleware(), k8sWorkloadCtrl.DeleteDaemonSet)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/daemonsets/:daemonSetName/restart", middleware.AuthMiddleware(), k8sWorkloadCtrl.RestartDaemonSet)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/jobs", middleware.AuthMiddleware(), k8sWorkloadCtrl.CreateJob)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/jobs/:jobName", middleware.AuthMiddleware(), k8sWorkloadCtrl.UpdateJob)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/jobs/:jobName", middleware.AuthMiddleware(), k8sWorkloadCtrl.DeleteJob)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/cronjobs", middleware.AuthMiddleware(), k8sWorkloadCtrl.CreateCronJob)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/cronjobs/:cronJobName", middleware.AuthMiddleware(), k8sWorkloadCtrl.UpdateCronJob)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/cronjobs/:cronJobName", middleware.AuthMiddleware(), k8sWorkloadCtrl.DeleteCronJob)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName/history", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetDeploymentHistory)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName/revisions/:revision", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetDeploymentRevision)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName/rollback", middleware.AuthMiddleware(), k8sWorkloadCtrl.RollbackDeployment)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName/pause", middleware.AuthMiddleware(), k8sWorkloadCtrl.PauseDeployment)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName/resume", middleware.AuthMiddleware(), k8sWorkloadCtrl.ResumeDeployment)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/deployments/:deploymentName/rollout-status", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetDeploymentRolloutStatus)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/workloads/:type/:workloadName/pods", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetWorkloadPods)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pods", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetPods)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetPodDetail)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName", middleware.AuthMiddleware(), k8sWorkloadCtrl.DeletePod)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName/logs", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetPodLogs)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName/events", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetPodEvents)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName/yaml", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetPodYaml)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName/yaml", middleware.AuthMiddleware(), k8sWorkloadCtrl.UpdatePodYaml)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/pods/yaml", middleware.AuthMiddleware(), k8sWorkloadCtrl.CreatePodFromYAML)

	router.GET("/k8s/cluster/:id/events", middleware.AuthMiddleware(), k8sEventsCtrl.GetClusterEvents)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/events", middleware.AuthMiddleware(), k8sEventsCtrl.GetEvents)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName/terminal", middleware.AuthMiddleware(), k8sTerminalCtrl.ConnectPodTerminal)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName/containers", middleware.AuthMiddleware(), k8sTerminalCtrl.GetPodContainers)
	router.POST("/k8s/cluster/:id/kubectl", middleware.AuthMiddleware(), k8sKubectlCtrl.ExecuteKubectl)
	router.GET("/k8s/cluster/:id/kubectl/terminal", middleware.AuthMiddleware(), k8sKubectlCtrl.ConnectKubectlTerminal)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pods/:podName/metrics", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetPodMetrics)
	router.GET("/k8s/cluster/:id/nodes/:nodeName/metrics", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetNodeMetrics)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/metrics", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetNamespaceMetrics)

	router.POST("/k8s/cluster/:id/yaml/validate", middleware.AuthMiddleware(), k8sWorkloadCtrl.ValidateYAML)
	router.POST("/k8s/cluster/:id/apply", middleware.AuthMiddleware(), k8sApplyCtrl.ApplyManifest)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/workload-yaml/:workloadType/:workloadName", middleware.AuthMiddleware(), k8sWorkloadCtrl.GetWorkloadYaml)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/workload-yaml", middleware.AuthMiddleware(), k8sWorkloadCtrl.UpdateWorkloadYaml)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/services", middleware.AuthMiddleware(), k8sServiceCtrl.GetServices)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/services/:serviceName", middleware.AuthMiddleware(), k8sServiceCtrl.GetServiceDetail)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/services", middleware.AuthMiddleware(), k8sServiceCtrl.CreateService)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/services/:serviceName", middleware.AuthMiddleware(), k8sServiceCtrl.UpdateService)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/services/:serviceName", middleware.AuthMiddleware(), k8sServiceCtrl.DeleteService)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/services/:serviceName/yaml", middleware.AuthMiddleware(), k8sServiceCtrl.GetServiceYaml)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/services/:serviceName/yaml", middleware.AuthMiddleware(), k8sServiceCtrl.UpdateServiceYaml)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/services/:serviceName/events", middleware.AuthMiddleware(), k8sServiceCtrl.GetServiceEvents)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/ingresses", middleware.AuthMiddleware(), k8sIngressCtrl.GetIngresses)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/ingresses/:ingressName", middleware.AuthMiddleware(), k8sIngressCtrl.GetIngressDetail)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/ingresses", middleware.AuthMiddleware(), k8sIngressCtrl.CreateIngress)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/ingresses/test-backend", middleware.AuthMiddleware(), k8sIngressCtrl.TestIngressBackend)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/ingresses/:ingressName", middleware.AuthMiddleware(), k8sIngressCtrl.UpdateIngress)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/ingresses/:ingressName", middleware.AuthMiddleware(), k8sIngressCtrl.DeleteIngress)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/ingresses/:ingressName/yaml", middleware.AuthMiddleware(), k8sIngressCtrl.GetIngressYaml)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/ingresses/:ingressName/yaml", middleware.AuthMiddleware(), k8sIngressCtrl.UpdateIngressYaml)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/ingresses/:ingressName/events", middleware.AuthMiddleware(), k8sIngressCtrl.GetIngressEvents)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/ingresses/:ingressName/monitoring", middleware.AuthMiddleware(), k8sIngressCtrl.GetIngressMonitoring)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pvcs", middleware.AuthMiddleware(), k8sStorageCtrl.GetPVCs)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pvcs/:pvcName", middleware.AuthMiddleware(), k8sStorageCtrl.GetPVCDetail)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/pvcs", middleware.AuthMiddleware(), k8sStorageCtrl.CreatePVC)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/pvcs/:pvcName", middleware.AuthMiddleware(), k8sStorageCtrl.UpdatePVC)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/pvcs/:pvcName", middleware.AuthMiddleware(), k8sStorageCtrl.DeletePVC)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/pvcs/:pvcName/yaml", middleware.AuthMiddleware(), k8sStorageCtrl.GetPVCYaml)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/pvcs/:pvcName/yaml", middleware.AuthMiddleware(), k8sStorageCtrl.UpdatePVCYaml)

	router.GET("/k8s/cluster/:id/pvs", middleware.AuthMiddleware(), k8sStorageCtrl.GetPVs)
	router.GET("/k8s/cluster/:id/pvs/:pvName", middleware.AuthMiddleware(), k8sStorageCtrl.GetPVDetail)
	router.POST("/k8s/cluster/:id/pvs", middleware.AuthMiddleware(), k8sStorageCtrl.CreatePV)
	router.PUT("/k8s/cluster/:id/pvs/:pvName", middleware.AuthMiddleware(), k8sStorageCtrl.UpdatePV)
	router.DELETE("/k8s/cluster/:id/pvs/:pvName", middleware.AuthMiddleware(), k8sStorageCtrl.DeletePV)
	router.GET("/k8s/cluster/:id/pvs/:pvName/yaml", middleware.AuthMiddleware(), k8sStorageCtrl.GetPVYaml)
	router.PUT("/k8s/cluster/:id/pvs/:pvName/yaml", middleware.AuthMiddleware(), k8sStorageCtrl.UpdatePVYaml)

	router.GET("/k8s/cluster/:id/storageclasses", middleware.AuthMiddleware(), k8sStorageCtrl.GetStorageClasses)
	router.GET("/k8s/cluster/:id/storageclasses/:storageClassName", middleware.AuthMiddleware(), k8sStorageCtrl.GetStorageClassDetail)
	router.POST("/k8s/cluster/:id/storageclasses", middleware.AuthMiddleware(), k8sStorageCtrl.CreateStorageClass)
	router.PUT("/k8s/cluster/:id/storageclasses/:storageClassName", middleware.AuthMiddleware(), k8sStorageCtrl.UpdateStorageClass)
	router.DELETE("/k8s/cluster/:id/storageclasses/:storageClassName", middleware.AuthMiddleware(), k8sStorageCtrl.DeleteStorageClass)
	router.GET("/k8s/cluster/:id/storageclasses/:storageClassName/yaml", middleware.AuthMiddleware(), k8sStorageCtrl.GetStorageClassYaml)
	router.PUT("/k8s/cluster/:id/storageclasses/:storageClassName/yaml", middleware.AuthMiddleware(), k8sStorageCtrl.UpdateStorageClassYaml)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/configmaps", middleware.AuthMiddleware(), k8sConfigCtrl.GetConfigMaps)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/configmaps/:configMapName", middleware.AuthMiddleware(), k8sConfigCtrl.GetConfigMapDetail)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/configmaps", middleware.AuthMiddleware(), k8sConfigCtrl.CreateConfigMap)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/configmaps/:configMapName", middleware.AuthMiddleware(), k8sConfigCtrl.UpdateConfigMap)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/configmaps/:configMapName", middleware.AuthMiddleware(), k8sConfigCtrl.DeleteConfigMap)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/configmaps/:configMapName/yaml", middleware.AuthMiddleware(), k8sConfigCtrl.GetConfigMapYaml)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/configmaps/:configMapName/yaml", middleware.AuthMiddleware(), k8sConfigCtrl.UpdateConfigMapYaml)

	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/secrets", middleware.AuthMiddleware(), k8sConfigCtrl.GetSecrets)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/secrets/:secretName", middleware.AuthMiddleware(), k8sConfigCtrl.GetSecretDetail)
	router.POST("/k8s/cluster/:id/namespaces/:namespaceName/secrets", middleware.AuthMiddleware(), k8sConfigCtrl.CreateSecret)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/secrets/:secretName", middleware.AuthMiddleware(), k8sConfigCtrl.UpdateSecret)
	router.DELETE("/k8s/cluster/:id/namespaces/:namespaceName/secrets/:secretName", middleware.AuthMiddleware(), k8sConfigCtrl.DeleteSecret)
	router.GET("/k8s/cluster/:id/namespaces/:namespaceName/secrets/:secretName/yaml", middleware.AuthMiddleware(), k8sConfigCtrl.GetSecretYaml)
	router.PUT("/k8s/cluster/:id/namespaces/:namespaceName/secrets/:secretName/yaml", middleware.AuthMiddleware(), k8sConfigCtrl.UpdateSecretYaml)
}
