// 系统常量
// author xiaoRui

package constant

const (
	ContextKeyUserObj      = "authedUserObj"
	LOGIN_CODE             = "login_code:"
	INVALID_PARAMS         = 400
	GROUP_EXIST            = 415
	ECS_AUTH_CREATE_FAILED = 416
	ECS_AUTH_UPDATE_FAILED = 417
	ECS_AUTH_DELETE_FAILED = 418
	ECS_AUTH_NAME_EXISTS   = 419
	ECS_AUTH_NOT_FOUND     = 420

	// CMDB 主机相关错误码
	CMDB_HOST_CREATE_FAILED        = 421
	CMDB_HOST_UPDATE_FAILED        = 422
	CMDB_HOST_DELETE_FAILED        = 423
	CMDB_HOST_NAME_EXISTS          = 424
	CMDB_HOST_NOT_FOUND            = 425
	CMDB_HOST_AUTH_NOT_FOUND       = 426
	CMDB_HOST_AUTH_FAILED          = 427
	CMDB_HOST_SYNC_FAILED          = 428
	CMDB_IMPORT_TASK_CREATE_FAILED = 429
	FILE_OPERATION_ERROR           = 430 // 文件操作失败

	// CMDB 网络设备相关错误码
	CMDB_DEVICE_CREATE_FAILED = 431
	CMDB_DEVICE_UPDATE_FAILED = 432
	CMDB_DEVICE_DELETE_FAILED = 433
	CMDB_DEVICE_NOT_FOUND     = 434
	CMDB_DEVICE_QUERY_FAILED  = 435

	// Kubernetes 集群相关常量
	KUBE_CLUSTER_CODE       = "kube_cluster:"
	KUBE_CLUSTER_CACHE_CODE = "kube_cluster_cache:"
)
