import request from '@/utils/request';
export const listK8sClustersApi = () => request.get('/v1/k8s/clusters');
export const createK8sClusterApi = (data) => request.post('/v1/k8s/clusters', data);
export const updateK8sClusterApi = (id, data) => request.put(`/v1/k8s/clusters/${id}`, data);
export const deleteK8sClusterApi = (id) => request.delete(`/v1/k8s/clusters/${id}`);
export const testK8sClusterApi = (id) => request.post(`/v1/k8s/clusters/${id}/test`);
export const getK8sClusterApi = (id) => request.get(`/v1/k8s/clusters/${id}`);
export const listK8sNamespacesApi = (clusterId) => request.get(`/v1/k8s/clusters/${clusterId}/namespaces`);
export const listK8sNodesApi = (clusterId) => request.get(`/v1/k8s/clusters/${clusterId}/nodes`);
export const cordonK8sNodeApi = (clusterId, name) => request.put(`/v1/k8s/clusters/${clusterId}/nodes/${name}/cordon`);
export const uncordonK8sNodeApi = (clusterId, name) => request.put(`/v1/k8s/clusters/${clusterId}/nodes/${name}/uncordon`);
export const drainK8sNodeApi = (clusterId, name) => request.post(`/v1/k8s/clusters/${clusterId}/nodes/${name}/drain`);
export const listDeploymentsApi = (clusterId, ns) => request.get(`/v1/k8s/clusters/${clusterId}/ns/${ns}/deployments`);
export const getDeploymentApi = (clusterId, ns, name) => request.get(`/v1/k8s/clusters/${clusterId}/ns/${ns}/deployments/${name}`);
export const createDeploymentApi = (clusterId, ns, data) => request.post(`/v1/k8s/clusters/${clusterId}/ns/${ns}/deployments`, data);
export const updateDeploymentApi = (clusterId, ns, name, data) => request.put(`/v1/k8s/clusters/${clusterId}/ns/${ns}/deployments/${name}`, data);
export const deleteDeploymentApi = (clusterId, ns, name) => request.delete(`/v1/k8s/clusters/${clusterId}/ns/${ns}/deployments/${name}`);
export const scaleDeploymentApi = (clusterId, ns, name, replicas) => request.put(`/v1/k8s/clusters/${clusterId}/ns/${ns}/deployments/${name}/scale`, { replicas });
export const restartDeploymentApi = (clusterId, ns, name) => request.post(`/v1/k8s/clusters/${clusterId}/ns/${ns}/deployments/${name}/restart`);
export const listPodsApi = (clusterId, ns) => request.get(`/v1/k8s/clusters/${clusterId}/ns/${ns}/pods`);
export const getPodLogsApi = (clusterId, ns, pod, params) => request.get(`/v1/k8s/clusters/${clusterId}/ns/${ns}/pods/${pod}/logs`, { params });
export const deletePodApi = (clusterId, ns, pod) => request.delete(`/v1/k8s/clusters/${clusterId}/ns/${ns}/pods/${pod}`);
export const listServicesApi = (clusterId, ns) => request.get(`/v1/k8s/clusters/${clusterId}/ns/${ns}/services`);
export const listIngressesApi = (clusterId, ns) => request.get(`/v1/k8s/clusters/${clusterId}/ns/${ns}/ingresses`);
export const listConfigMapsApi = (clusterId, ns) => request.get(`/v1/k8s/clusters/${clusterId}/ns/${ns}/configmaps`);
export const saveConfigMapApi = (clusterId, ns, data) => request.post(`/v1/k8s/clusters/${clusterId}/ns/${ns}/configmaps`, data);
export const deleteConfigMapApi = (clusterId, ns, name) => request.delete(`/v1/k8s/clusters/${clusterId}/ns/${ns}/configmaps/${name}`);
export const listSecretsApi = (clusterId, ns, decode = false) => request.get(`/v1/k8s/clusters/${clusterId}/ns/${ns}/secrets`, { params: { decode: decode ? 1 : 0 } });
export const saveSecretApi = (clusterId, ns, data) => request.post(`/v1/k8s/clusters/${clusterId}/ns/${ns}/secrets`, data);
export const deleteSecretApi = (clusterId, ns, name) => request.delete(`/v1/k8s/clusters/${clusterId}/ns/${ns}/secrets/${name}`);
