import request from '@/utils/request';
export const listUsersApi = (params) => request.get('/v1/system/users', { params });
export const createUserApi = (data) => request.post('/v1/system/users', data);
export const updateUserApi = (id, data) => request.put(`/v1/system/users/${id}`, data);
export const deleteUserApi = (id) => request.delete(`/v1/system/users/${id}`);
export const changeUserPasswordApi = (id, data) => request.put(`/v1/system/users/${id}/password`, data);
export const assignUserRolesApi = (id, role_ids) => request.put(`/v1/system/users/${id}/roles`, { role_ids });
export const listRolesApi = () => request.get('/v1/system/roles');
export const createRoleApi = (data) => request.post('/v1/system/roles', data);
export const updateRoleApi = (id, data) => request.put(`/v1/system/roles/${id}`, data);
export const deleteRoleApi = (id) => request.delete(`/v1/system/roles/${id}`);
export const assignRoleMenusApi = (id, menu_ids) => request.put(`/v1/system/roles/${id}/menus`, { menu_ids });
export const listMenusApi = () => request.get('/v1/system/menus');
export const menuTreeApi = () => request.get('/v1/system/menus/tree');
export const createMenuApi = (data) => request.post('/v1/system/menus', data);
export const updateMenuApi = (id, data) => request.put(`/v1/system/menus/${id}`, data);
export const deleteMenuApi = (id) => request.delete(`/v1/system/menus/${id}`);
export const listDepartmentsApi = () => request.get('/v1/system/departments');
export const createDepartmentApi = (data) => request.post('/v1/system/departments', data);
export const updateDepartmentApi = (id, data) => request.put(`/v1/system/departments/${id}`, data);
export const deleteDepartmentApi = (id) => request.delete(`/v1/system/departments/${id}`);
